'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BookingPage

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lbl_choose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_choose As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''drp_school control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_school As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''drp_court control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_court As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cal_booking_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cal_booking_date As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''lbl_courtTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_courtTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''start_time_hr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents start_time_hr As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''start_time_ampm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents start_time_ampm As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''end_time_hr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents end_time_hr As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''end_time_ampm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents end_time_ampm As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chk_nextDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_nextDay As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''drp_card_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_card_type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_cardNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cardNum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cal_expire_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cal_expire_date As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''txt_security control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_security As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_donate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_donate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_book control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_book As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_return control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_return As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_results control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_results As Global.System.Web.UI.WebControls.Label
End Class
